### ISSUE TITLE
Odd results of toggling "Extinct" flag

### ISSUE THREAD

**Issue by dhobern** [CatalogueOfLife/portal-components#16]
On the https://www.catalogue.life/ homepage, with Extinct selected, I typed "Pterophorus o" and got many suggestions:

![image](https://user-images.githubusercontent.com/26148454/101105317-569ecb00-3621-11eb-9e87-5bcd1dc82ee6.png)

I selected "Pterophorus oligocenicus" to check it was marked as extinct.

I then deselected the "Extinct" flag and received a yellow warning message "Cannot find taxon 4Q2DS in tree 😥".

I then cleared the searchbox text and retyped "Pterophorus o" - autoselect suggestions appeared until I hit the o, at which point they disappeared - no suggestions at all.

I selected "Extinct" again, deleted the last few letters and retyped them and all the suggestions were back again.

**Comment by mdoering** [comment]
See also https://github.com/CatalogueOfLife/portal/issues/55 whether we really want to be able to search for all taxa in the tree or rather restrict this to higher taxa

**Comment by mdoering** [comment]
The behavior you see Donald is pretty much expected. But:
 - the suggest does not use the extinct label which would help
 - @thomasstjerne should we allow to deselect extinct when the current taxon is an extinct one? Obviously this calls for trouble

**Comment by dhobern** [comment]
The behaviour is not as expected. Maybe I wasn't clear. Once the name was no longer part of the search results, NO suggestions were offered for "Pterophorus o" whereas many were offered while Pterophorus oligocenicus was included (the one extinct species).

My impression was that the service returning the autosuggest values was broken and returned nothing if the search included an extinct species and that species was excluded using the flag. Check that service.

**Comment by mdoering** [comment]
You are right. Something wrong.

I think the reason are the 3 possible states (extinct, not extinct and NULL/unknown) and how the UI calls the API.
In the beginning the UI does not include any `extinct` parameter which gets interpreted from the UI as to allow any of the 3 states. If you then uncheck extinct, it passes extinct=false to the backend which excludes extinct, but allows the 2 others.
When toggling again the UI now passes extinct=true, which means only species which are explicitly known to be not extinct - which most aren't. It will exclude both extinct and unknown/null values and hence return nothing.

@thomasstjerne can we make the UI pass only ever `extinct=false` or `extinct=` ?

**Comment by thomasstjerne** [comment]
As you see here: https://api.catalogueoflife.org/dataset/2242/nameusage/suggest?fuzzy=false&limit=25&q=Pterophorus%20o&extinct=false
a query for "Pterophorus o" with the `extinct=false` toggle returns no results:   

The UI only uses `extinct=false`. I dont think it ever sends `extinct=true`.

So I would say the behaviour is expected, at least from the UI side. I dont know if there are any extant taxa matching "Pterophorus o", though.

The error message for a missing tree node is very general and inherited from the ChecklistBank UI where there could be all kinds of reasons why a node is missing, most of which the UI cant determine.
In the portal, this specific case is the only one that I can think of where a user can actually bring the tree into a state where a node is missing, and I can adapt the error message could be a bit more informative.

**Comment by mdoering** [comment]
It does send extinct=true in my browser if you toggle the extinct a few times. Can we avoid that?

**Comment by mdoering** [comment]
https://api.catalogueoflife.org/dataset/2242/nameusage/suggest?fuzzy=false&limit=25&q=Pterophorus%20o&extinct=
https://api.catalogueoflife.org/dataset/2242/nameusage/suggest?fuzzy=false&limit=25&q=Pterophorus%20o&extinct=false
https://api.catalogueoflife.org/dataset/2242/nameusage/suggest?fuzzy=false&limit=25&q=Pterophorus%20o&extinct=true

We need to avoid sending extinct=false, it should be true or an empty param when the check box is unchecked.

**Comment by thomasstjerne** [comment]
> It does send extinct=true and also extinct=false in my browser if you toggle the extinct a few times. Can we avoid sending extinct=false?

I only see [one extinct=true in the logs](https://logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-24h,to:now))&_a=(columns:!(level,datasetKey,service,logger_name,message),filters:!(),index:'37c669c0-2a5c-11eb-9ca0-ddc1af98892f',interval:auto,query:(language:lucene,query:%22extinct%3Dtrue%22),sort:!())), and I know i did one direct request to the API for testing around that time. But extinct=false is[ all over the logs](https://logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-24h,to:now))&_a=(columns:!(level,datasetKey,service,logger_name,message),filters:!(),index:'37c669c0-2a5c-11eb-9ca0-ddc1af98892f',interval:auto,query:(language:lucene,query:%22extinct%3Dfalse%22),sort:!()))

**Comment by thomasstjerne** [comment]
> @thomasstjerne can we make the UI pass only ever `extinct=false` or `extinct=` ?

> We need to avoid sending extinct=false, it should be true or an empty param when the check box is unchecked.

I am a bit confused about this. I would expect passing `extinct=false` would filter out taxa explicitly marked as extinct.
And if the param `extinct` is omitted, it should return any taxon, extinct or not.
But the service seems to exclude taxa if they have `NULL` in the `extinct` field in the DB.

**Comment by mdoering** [comment]
I find this confusing myself. Let me summarize the intention again:
if extinct is:
 - **true** only shows taxa explicitly marked as extinct
 - **false** only shows taxa explicitly marked as NOT extinct
 - **EMPTY** show all taxa, ignoring the extinct property

It seems the API does filter the last one to show all taxa that have extinct=NULL - which is wrong.

So. If I had fixed that API bug would things work as expected?
Or should we maybe change the API to a simpler boolean model with 2 states (true/false) only and if so, what would that be?

**Comment by mdoering** [comment]
The idea in the UI was to have a checkbox that
 a) checked = show all taxa including extinct
 b) unchecked = show only taxa that have extinct=false or NULL

That is correct, right? And it should be the same for the search and the tree browser.

Ah, it should be the same as for the kingdom counts.

Request URL: https://api.catalogueoflife.org/dataset/2242/nameusage/search?field&limit=50&offset=0&q=Felis&sortBy=taxonomic&status=_NOT_NULL

**Comment by mdoering** [comment]
It makes a difference whether no extinct parameter is given or `extinct=` without any value.
The first indeed shows all, the later filters for NULL only:

https://api.catalogueoflife.org/dataset/2242/nameusage/suggest?q=Pterophorus%20ol
https://api.catalogueoflife.org/dataset/2242/nameusage/suggest?q=Pterophorus%20ol&extinct=

**Comment by mdoering** [comment]
That means if extinct is:

 - **extinct=true** only shows taxa explicitly marked as extinct
 - **extinct=false** only shows taxa explicitly marked as NOT extinct
 - **extinct=** only shows taxa marked as unknown / NULL
 - **not present** show all taxa, ignoring the extinct property

**Comment by mdoering** [comment]
whats the conclusion?

**Comment by thomasstjerne** [comment]
I think the most common use case here is "Dont give me extinct species".
This is currently only accomplished by sending `extinct=false&extinct=` (right ???) 

We may want to have a more intuitive way of doing that in the future, but we can leave it for now.

The toggle on the COL website will send `extinct=false&extinct=` of the "include extinct" is unchecked

**Comment by mdoering** [comment]
that is for all suggest, tree and search?
