### ISSUE TITLE
citations isn't rendered correctly

### ISSUE THREAD

**Issue by MortenHofft** [CatalogueOfLife/portal-components#19]
e.g. https://hp-legume.gbif-staging.org/taxonomy/browse?taxonKey=30032383-2

shows as 
<img width="1085" alt="Screenshot 2021-07-01 at 17 09 12" src="https://user-images.githubusercontent.com/6759267/124147543-14dae380-da8f-11eb-9d08-76667d3049c8.png">

**Comment by thomasstjerne** [comment]
@MortenHofft fixed in v1.0
