### ISSUE TITLE
Possibility to use a JavaScript callback in ColBrowser.Tree ?

### ISSUE THREAD

**Issue by ftheeten** [CatalogueOfLife/portal-components#27]
Dear all,

I'm using the ColBrowser.Tree in a small web application for the CETAF and DEST. It works great and is easy to use. Would it be possible to link the selected taxa to a JavaScript callback (using the **_catalogueKey_** value as parameter) instead of opening a webpage with **_pathToTaxon_**? This would ease serialization of the CoL key in other databases or apps (e.G to enrich, check or annotate data).  I would be glad to contribute to this development, but I'm not familiar with React :(

I found a (rather dirty) workaround solution (see below) by using JQuery and the MutationObserver to disable the **href** attribute of the links, but a more integrated solution would be more reliable and could increase the usability of this nice control.

```
var  callback_taxa=function(col_key, taxa_term)
{
	//do stuff
}

function onElementInserted(containerSelector) 
{
    var onMutationsObserved = function(mutations) {
        mutations.forEach(function(mutation) {
            if (mutation.addedNodes.length) {
                var elements = $(mutation.addedNodes);                 
                 var anchors=$(elements.get(0)).find("a");
                 anchors.each(function( index ) 
		 {                 
                   var href=$( this ).attr("href");
                   var hreflen=href.split("/");
                    href=hreflen[hreflen.length-1];
                     //$(this).removeAttr('href');
                    $(this).attr('col_key', href);
                     $(this).click(function(e) 
		    {
                        //disable href click
                        e.preventDefault();
                        //custom callback
                        callback_taxa($( this ).attr("col_key"),$( this ).text());
                       //needed with JQuery 
                       return false;
                        });
                  });                
            }
        });
    };
    var target = $(containerSelector)[0];
    var config = { childList: true, subtree: true };
    var MutationObserver = window.MutationObserver || window.WebKitMutationObserver;
    var observer = new MutationObserver(onMutationsObserved);    
    observer.observe(target, config);

}

onElementInserted('body');
```

**Comment by thomasstjerne** [comment]
Hi @ftheeten 
This is a good idea, thanks! 
I have made a pre-release here https://github.com/CatalogueOfLife/portal-components/releases/tag/v1.2.7-beta
You should simply be able to give a `function` instead of a `string` in the `pathToTaxon` attribute like shown below. Please test and see if it fits your needs. 

Include this pre-release:
`<script src="https://cdn.jsdelivr.net/gh/CatalogueOfLife/portal-components@v1.2.7-beta/umd/col-browser.min.js" ></script>`

And then:
```
<div id="tree"></div> <!- Dom element for the tree to attach to -->
............
<script >
'use strict';
var callBack = function(taxonKey){
  alert('This seems to work, key is ' + taxonKey)
// Do something with the taxonKey
}
const e = React.createElement;
class Tree extends React.Component {

    render() {

      return e(
        ColBrowser.Tree,
        { catalogueKey: 9999,
          pathToTaxon: callBack,
          defaultTaxonKey: 'urn:lsid:indexfungorum.org:names:814401',
          pathToDataset: '/sourcedatasets/' }
      );
    }
  }

const domContainer = document.querySelector('#tree');
ReactDOM.render(e(Tree), domContainer);
</script>
```

**Comment by ftheeten** [comment]
Hi @thomasstjerne 

Thanks for your speedy reply ! This works very well ! Here is an example of callback adding the key to a select2 control.

```
var go_to_anchor=function(anchor) {
  var loc = document.location.toString().split('#')[0];
  document.location = loc + '#' + anchor;
  return false;
}

var callBack = function(taxonKey)
{
  var newOption = new Option(taxonKey, taxonKey, true, true);
    // Append it to the select
  $('#selected_taxa').append(newOption).trigger('change');
  go_to_anchor("selected_taxa_link");
}
```

![test_col](https://user-images.githubusercontent.com/13105610/171623313-61e04670-8a6a-4651-9195-af9fa28ce208.png)
!
