### ISSUE TITLE
Legume Data Portal taxon page COL id error

### ISSUE THREAD

**Issue by AnneBruneau** [CatalogueOfLife/portal-components#38]
On the taxon page for each genus on the legume data portal, the first line states COL identifier. This is no longer a COL identifier, it is the identifier from WCVP. Would it be possible to change "COL id" to "WCVP id" ?

https://legume.hp.gbif-staging.org/taxonomy/taxon/611079
https://www.checklistbank.org/dataset/2304/taxon/611079

thank you! Anne

**Comment by mdoering** [comment]
See https://github.com/CatalogueOfLife/portal/issues/162

@thomasstjerne would it be possible to make the component configurable for the identifier label so we can use COL Identifier or WCVP Identifier and default to just "Identifier"?
